### ISSUE TITLE
Not utilizing the generated views

### ISSUE THREAD

**Issue by Artforge** [rymai/devise_invitable#3]
I'm trying to use devise_invitable (in rails 3.0) and when I go and edit the generated views, it doesn't seem to be picking up the changes (tried all manner of rebooting the web server)

**Comment by rymai** [comment]
Have you followed Devise's instructions:

  If you have more than one role in your application (such as "User" and "Admin"), you will notice that Devise uses the same views for all roles. Fortunately, Devise offers an easy way to customize views. All you need to do is set "config.scoped_views = true" inside "config/initializers/devise.rb".

All is working as expected when I do the required steps on a fresh app.
